#!/bin/bash

# Copying files.
sudo cp /etc/network/interfaces /etc/network/interface.bak
sudo cp ../Backup_configs/interfaces /etc/network/

sudo cp /etc/rc.local /etc/rc.local.bak
sudo cp ../Backup_configs/rc.local /etc/

sudo cp /etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf.bk
sudo cp ../Backup_configs/wpa_supplicant.conf /etc/wpa_supplicant/

# Cloning gits.
bash /home/pi/Apts/Git_Clone
